[package]
name = "traefik-multi-host-mapper"
version = "0.4.0"
edition = "2021"


[dependencies]
toml = "0.8"
serde = "1.0"
serde_json = "1.0"

serde_derive = "1.0"
clap = "4.5"
actix-web = "4.0"
env_logger = "0.11"
reqwest = { version = "0.12", features = ["json"] }
