[server.public]
ip = "192.168.50.6"

[server.public.jellystat]
port = 5009

[server.public.audiobookshelf]
port = 5001

[server.public.sonarr]
port = 5004
authentik = true

[server.public.torrent]
port = 5002
authentik = true

[server.public.radarr]
port = 5003

[server.public.readarr]
port = 5005

[server.public.wizarr]
port = 5006

[server.public.prowlarr]
port = 5007
authelia = true

[server.public.freshrss]
port = 5010

[server.public.jellyseerr]
port = 5008

[server.public.bazarr]
port = 5012
authelia = true

[server.public.pinchflat]
port = 8945
authelia = true

[server.public.tandoor]
port = 8946
authelia = false
authentik = true
extra_domains = ["recept.hugopersson.com"]


[server.laptop]
ip = "192.168.50.2"

[server.laptop.zigbee2mqtt]
port = 5002
authelia = true

[server.laptop.home]
port = 8123

[server.laptop.cronicle]
port = 3012
authelia = true

[server.laptop.firefly]
port = 5003
authelia = true

[server.laptop.firefly-importer]
port = 5006
authelia = true

[server.laptop.ghostfolio]
port = 5004

[server.media]
ip = "192.168.50.9"

[server.media.jellyfin]
port = 8096

[server.proxmox]
ip = "192.168.50.3"

[server.proxmox.proxmox]
port = 8006
https = true

[server.secure]
ip = "192.168.50.10"

[server.secure.paperless]
port = 5008

[server.secure.calibre]
port = 8083

[server.secure.couchdb]
port = 5005
