#!/bin/bash

# vim: filetype=sh

# If we have edited the config.toml file, run the validate command before comitting
if git diff --cached --name-only | grep -qE "config\.toml$"; then
  echo "Rust files staged, running cargo run -- validate..."
  if ! cargo run -- validate; then
    echo "Config is not valid, not committing. Fix and then commit."
    echo "Run 'cargo run -- validate' to see the errors"
    exit 1
  fi
fi

echo "Pre-commit hook passed."
